# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install dependencies
      run: |
        xcodebuild -version
        export GOARCH=arm64
        export GOOS=darwin
        export CGO_ENABLED=0
        export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        export CC=$(xcrun --sdk iphoneos -f clang)
        export CFLAGS="-s -w -arch arm64 -isysroot $SDKROOT"
        export CXXFLAGS="-s -w -arch arm64 -isysroot $SDKROOT"
        export CGO_LDFLAGS="-s -w -isysroot $SDKROOT"
        export CGO_CFLAGS="-s -w -isysroot $SDKROOT"
        go mod download

    - name: Build
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-musicfox-ios
        path: bin/
