name: iOS Build for go-musicfox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "^1.22.0"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        go mod download

    # Step 4: Build for iOS
    - name: Build for iOS
      run: |
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 make

    # Step 5: Upload the built binary as an artifact (optional)
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: go-musicfox-ios
        path: bin/

